server:
  port: 8085
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    tryItOutEnabled: true
    tagsSorter: alpha
    operationsSorter: method
    enabled: true
    path: /swagger-ui.html
    display-request-duration: true
    default-models-expand-depth: 1
    doc-expansion: none
  packages-to-scan: com.challenge.meli
  paths-to-match:
    - /api/**
    - /**
spring:
  application:
    name: meli
# I used generative AI to set up datasource properties
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true